In [6]:
import pandas as pd
import numpy as np
header_list = ["tweet_ID", "tweet_time","team","opponent", "week", "home_or_away","score","opponent_score","point_spread","over_under"]
df = pd.read_csv('nfl-tweets-v1.0/tweets.nfl.2011.weekly.csv', names=header_list)
tweets = df["tweet_ID"].tolist()

In [63]:
#2010
with open('2011lastwrite.txt', 'r') as readfile:
    f=readfile.readlines()
last_tweet = int(f[-1].split('\t')[0])
last_tweet_index = tweets.index(last_tweet)
with open('2011lastwrite(reverse).txt', 'r') as readfile:
    f=readfile.readlines()
last_tweet = int(f[-1].split('\t')[0])
last_tweet_index_reverse = tweets.index(last_tweet) + 1

In [ ]:
print(last_tweet_index,last_tweet_index_reverse)

In [64]:
print(last_tweet_index,last_tweet_index_reverse)

286706 238753

In [8]:
print(len(tweets))

185709

In [ ]:
291953283436545 #start of error

In [ ]:
999725155221504 #end of error

In [6]:
import pandas as pd
a = pd.read_csv("2010tweettext.txt",header = None, sep='\t',error_bad_lines=False)
b = pd.read_csv("2010tweettext(reverse).txt",header = None, sep='\t',error_bad_lines=False)
# then use concat?

b'Skipping line 3052: expected 2 fields, saw 3\nSkipping line 9654: expected 2 fields, saw 4\nSkipping line 32533: expected 2 fields, saw 3\nSkipping line 39832: expected 2 fields, saw 3\nSkipping line 55467: expected 2 fields, saw 3\nSkipping line 72215: expected 2 fields, saw 3\nSkipping line 73989: expected 2 fields, saw 3\nSkipping line 75357: expected 2 fields, saw 3\nSkipping line 78180: expected 2 fields, saw 3\nSkipping line 84434: expected 2 fields, saw 3\nSkipping line 87083: expected 2 fields, saw 3\nSkipping line 88713: expected 2 fields, saw 4\nSkipping line 92599: expected 2 fields, saw 3\nSkipping line 94905: expected 2 fields, saw 3\nSkipping line 95823: expected 2 fields, saw 3\nSkipping line 100512: expected 2 fields, saw 3\nSkipping line 102775: expected 2 fields, saw 3\nSkipping line 103001: expected 2 fields, saw 5\nSkipping line 110287: expected 2 fields, saw 3\nSkipping line 113511: expected 2 fields, saw 3\nSkipping line 118673: expected 2 fields, saw 3\nSkipping line 122583: expected 2 fields, saw 3\nSkipping line 124104: expected 2 fields, saw 3\n'
b'Skipping line 2185: expected 2 fields, saw 3\nSkipping line 8440: expected 2 fields, saw 3\nSkipping line 11089: expected 2 fields, saw 3\nSkipping line 12719: expected 2 fields, saw 4\nSkipping line 16604: expected 2 fields, saw 3\nSkipping line 18910: expected 2 fields, saw 3\nSkipping line 19828: expected 2 fields, saw 3\nSkipping line 24517: expected 2 fields, saw 3\nSkipping line 26780: expected 2 fields, saw 3\nSkipping line 27006: expected 2 fields, saw 5\nSkipping line 34292: expected 2 fields, saw 3\nSkipping line 37517: expected 2 fields, saw 3\nSkipping line 42679: expected 2 fields, saw 3\nSkipping line 46588: expected 2 fields, saw 3\n'

In [3]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
def get_sentiment(tweet):
  analyzer = SentimentIntensityAnalyzer()
  return analyzer.polarity_scores(tweet)['compound']

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/stanierc17/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [51]:
%%time
tweets2010['sent'] = tweets2010['text'].apply(lambda x: get_sentiment(str(x)))

CPU times: user 29min 51s, sys: 37.6 s, total: 30min 28s
Wall time: 32min 30s

In [55]:
sent = tweets2010['sent'].tolist()

In [50]:
print(a.groupby('sent').count().to_string())

          id  text
sent
-0.8176    1     1
-0.8122    1     1
-0.8074    1     1
-0.8020    1     1
-0.7906    1     1
-0.7721    1     1
-0.7500    1     1
-0.7450    2     2
-0.7430    4     4
-0.7351    1     1
-0.7269    1     1
-0.6908    1     1
-0.6808    1     1
-0.6797    1     1
-0.6739    1     1
-0.6715    1     1
-0.6696    1     1
-0.6633    1     1
-0.6597    1     1
-0.6437    1     1
-0.6259    1     1
-0.6249    1     1
-0.6239    1     1
-0.6124    1     1
-0.6103    1     1
-0.5994    2     2
-0.5859    1     1
-0.5848    1     1
-0.5835    1     1
-0.5789    1     1
-0.5719    2     2
-0.5707    1     1
-0.5574    8     8
-0.5563    1     1
-0.5542    1     1
-0.5423    3     3
-0.5400    1     1
-0.5399    1     1
-0.5267    1     1
-0.5256    1     1
-0.5255    2     2
-0.5112    1     1
-0.5106    1     1
-0.4995    1     1
-0.4981    1     1
-0.4973    1     1
-0.4939    1     1
-0.4926    1     1
-0.4767    2     2
-0.4724    1     1
-0.4606    1     1
-0.4588    3     3
-0.4574    1     1
-0.4559    1     1
-0.4466    2     2
-0.4418    1     1
-0.4404    7     7
-0.4389    2     2
-0.4374    1     1
-0.4215    2     2
-0.4019    4     4
-0.3891    1     1
-0.3818    1     1
-0.3749    1     1
-0.3736    2     2
-0.3707    1     1
-0.3612    6     6
-0.3595    1     1
-0.3561    1     1
-0.3557    1     1
-0.3400    4     4
-0.3382    2     2
-0.3182    8     8
-0.3129    1     1
-0.2960   14    14
-0.2942    1     1
-0.2808    1     1
-0.2755    2     2
-0.2732   13    13
-0.2728    1     1
-0.2584    1     1
-0.2500    4     4
-0.2263    3     3
-0.2244    2     2
-0.2225    1     1
-0.2146    2     2
-0.2052    1     1
-0.2023    3     3
-0.1796    1     1
-0.1779    1     1
-0.1613    1     1
-0.1531    3     3
-0.1526    1     1
-0.1376    1     1
-0.1343    1     1
-0.1280    4     4
-0.1260    1     1
-0.1154    2     2
-0.1027    7     7
-0.0772    3     3
-0.0572    2     2
-0.0516    4     4
-0.0258    1     1
 0.0000  444   444
 0.0085    1     1
 0.0258    5     5
 0.0366    1     1
 0.0516    2     2
 0.0772    9     9
 0.0857    1     1
 0.1007    1     1
 0.1027    2     2
 0.1111    1     1
 0.1197    1     1
 0.1280    3     3
 0.1511    1     1
 0.1531    3     3
 0.1561    1     1
 0.1680    2     2
 0.1759    1     1
 0.1779    1     1
 0.1860    1     1
 0.1974    1     1
 0.2023    6     6
 0.2025    1     1
 0.2206    1     1
 0.2263    4     4
 0.2342    1     1
 0.2481    1     1
 0.2500   10    10
 0.2714    2     2
 0.2732    2     2
 0.2824    1     1
 0.2869    1     1
 0.2924    1     1
 0.3035    2     2
 0.3094    1     1
 0.3147    1     1
 0.3164    1     1
 0.3182    6     6
 0.3365    1     1
 0.3382    1     1
 0.3387    1     1
 0.3400    8     8
 0.3595    1     1
 0.3612    7     7
 0.3802    2     2
 0.3818    2     2
 0.4005    1     1
 0.4019    4     4
 0.4144    1     1
 0.4145    1     1
 0.4184    1     1
 0.4199    1     1
 0.4215   10    10
 0.4280    1     1
 0.4374    3     3
 0.4404   13    13
 0.4482    1     1
 0.4559    1     1
 0.4574    5     5
 0.4588   10    10
 0.4767    3     3
 0.4926    3     3
 0.4939    6     6
 0.4995    1     1
 0.5040    1     1
 0.5093    2     2
 0.5106    4     4
 0.5255    1     1
 0.5267    1     1
 0.5269    1     1
 0.5376    1     1
 0.5461    1     1
 0.5473    1     1
 0.5504    1     1
 0.5526    3     3
 0.5538    1     1
 0.5550    1     1
 0.5562    2     2
 0.5574    1     1
 0.5609    1     1
 0.5638    1     1
 0.5665    1     1
 0.5719   10    10
 0.5826    2     2
 0.5859    5     5
 0.5893    1     1
 0.5951    1     1
 0.5974    1     1
 0.5980    1     1
 0.5983    1     1
 0.5994    9     9
 0.6114    1     1
 0.6124    1     1
 0.6131    1     1
 0.6166    1     1
 0.6209    2     2
 0.6239    1     1
 0.6249    6     6
 0.6289    1     1
 0.6322    1     1
 0.6331    1     1
 0.6341    1     1
 0.6351    1     1
 0.6360    1     1
 0.6369    4     4
 0.6486    2     2
 0.6529    1     1
 0.6580    1     1
 0.6588    1     1
 0.6597    2     2
 0.6643    1     1
 0.6696    1     1
 0.6697    1     1
 0.6705    1     1
 0.6808    6     6
 0.6892    1     1
 0.6893    1     1
 0.6900    1     1
 0.6908    2     2
 0.6940    1     1
 0.6988    1     1
 0.7003    2     2
 0.7067    1     1
 0.7081    1     1
 0.7088    1     1
 0.7111    1     1
 0.7177    1     1
 0.7184    1     1
 0.7213    1     1
 0.7243    1     1
 0.7269    3     3
 0.7284    1     1
 0.7311    1     1
 0.7345    1     1
 0.7351    3     3
 0.7371    1     1
 0.7405    2     2
 0.7424    1     1
 0.7592    1     1
 0.7633    1     1
 0.7650    1     1
 0.7717    2     2
 0.7772    1     1
 0.7783    2     2
 0.7845    1     1
 0.7847    1     1
 0.7876    1     1
 0.7887    1     1
 0.7946    1     1
 0.7959    1     1
 0.8020    3     3
 0.8074    1     1
 0.8114    2     2
 0.8122    1     1
 0.8225    1     1
 0.8233    1     1
 0.8239    1     1
 0.8253    1     1
 0.8271    2     2
 0.8309    1     1
 0.8346    1     1
 0.8402    1     1
 0.8442    1     1
 0.8558    1     1
 0.8564    1     1
 0.8585    1     1
 0.8614    1     1
 0.8622    1     1
 0.8687    1     1
 0.8779    1     1
 0.8786    1     1
 0.8788    1     1
 0.8807    1     1
 0.8832    1     1
 0.8873    1     1
 0.8958    1     1
 0.9015    1     1
 0.9124    1     1
 0.9134    2     2
 0.9136    1     1
 0.9172    2     2
 0.9183    1     1
 0.9286    1     1
 0.9296    1     1
 0.9325    1     1
 0.9382    1     1
 0.9499    1     1

In [42]:
tweets2010

                      id                                               text
0            22662042404  Can someone please tell me WTF the #Seahawks a...
1            22662135903  Q&A with Todd Haley - 8/31 #NFL #chiefs http:/...
2            22662138503  PFW Blog: Bodden done for the year #NFL #patri...
3            22662142404  Bomar the backup for Giants, for now #NFL #gia...
4            22662229101  #Packers made the right moves 2day. Tough deci...
...                  ...                                                ...
47241  19541631682220032  @Rozzell32 yea he do need to gone and drop dat...
47242  19541635893297152                 @seatownsports PLAYOFFS. #seahawks
47243  19541786770804737  Gonna eat this sammy, smoke fat blunt and play...
47244  19541799517298688  since atlanta is home of @cnn, would be cool i...
47245  19541807700381696  RT @NickyDiamonds: Black/Green @Currensy_Spitt...

[172958 rows x 2 columns]

In [54]:
type(get_sentiment('hello'))

float

In [57]:
sent.count(0.0)

69704

In [58]:
len(sent)

172958

In [1]:
# load additional module
import pickle

with open('2010missing_tweets', 'rb') as filehandle:
    # read the data as binary data stream
    missing_tweets = pickle.load(filehandle)

In [2]:
missing_tweets

['24392221907',
 '26120535807',
 '27732054256',
 '6702854446260224',
 '12221191439781888',
 '19754697975930880',
 '28569795588',
 '8554539028324352',
 '29627681986',
 '5715729466789888',
 '28560358965',
 '24748125908',
 '24959574700',
 '4144152803549184',
 '22665680004',
 '19595927073325057',
 '14519892317306880',
 '20984321170997248',
 '26555599202',
 '24895791205',
 '25679428007',
 '27593340215',
 '6389124827185152',
 '8641600334856193',
 '1292504192262144',
 '17807035470970880',
 '24706796702',
 '13137290226302976',
 '25676756703',
 '1721447491833856',
 '25033682504',
 '7854539168284672',
 '29396207956',
 '28717392490',
 '683894202441728',
 '27365796768',
 '24762508102',
 '19184746818961408',
 '24587782907',
 '18059243106074624',
 '28718718513',
 '28937004484',
 '25310206307',
 '29005768283',
 '28670661108',
 '2866102258372608',
 '1295943743836161',
 '29418445786',
 '26616868700',
 '29511275239',
 '23243365100',
 '14350601546637313',
 '25431059304',
 '20219598792036353',
 '25145754201',
 '19902471870615552',
 '5354067052204032',
 '20509970793496576',
 '25728026104',
 '27199842031',
 '11984603292106752',
 '27101605105',
 '11463028914528256',
 '26595895604',
 '413353184862208',
 '22765012104',
 '5725887827808256',
 '26768450808',
 '17056066034466816',
 '13091899514552320',
 '20895464756875264',
 '11997697699479553',
 '14002398947180544',
 '25376610505',
 '838752029122560',
 '27267756264',
 '24940245401',
 '6465066870243328',
 '12664407347699714',
 '25440797502',
 '28751260301',
 '15887432176115712',
 '16978068757286913',
 '20720151515111424',
 '19006493021966336',
 '24878714204',
 '24981074408',
 '25683045408',
 '15529813510983680',
 '25581879502',
 '10466747459051520',
 '3659203361120257',
 '27588637695',
 '24729014803',
 '28931207040',
 '18069024252366848',
 '4396176069623808',
 '4712632141479936',
 '14549424218841088',
 '1067383640821760',
 '22912349100',
 '20820747584798720',
 '29244221880',
 '8735493785124864',
 '15230671412797440',
 '1090817049493505',
 '8931166497275904',
 '29492428898',
 '27993436214',
 '29433055039',
 '25157454801',
 '24233021004',
 '17828837173760000',
 '29424782283',
 '589345954209792',
 '19523247980683264',
 '18860346773086208',
 '26846368003',
 '27986534554',
 '17030074201014273',
 '4284561466855425',
 '20279585891422208',
 '15526621347840000',
 '25229302600',
 '24412787507',
 '25327405702',
 '26645425006',
 '662423568650240',
 '20516522195685376',
 '1003340699803648',
 '15553179945009152',
 '27793259364',
 '24591093707',
 '17241903028244480',
 '27285514255',
 '4570994807144448',
 '23245268900',
 '24340955801',
 '4306195510730752',
 '20225865342259200',
 '24872692709',
 '11512777365520384',
 '7884964611751937',
 '28606638832',
 '6273387299078144',
 '10442600821559296',
 '27406840231',
 '927772054650880',
 '2609758913699840',
 '2896913724612608',
 '12261590967517184',
 '17224899634397184',
 '6762048918654976',
 '19485419485794304',
 '11447228912635904',
 '29401349695',
 '15892666873024512',
 '4361765886369792',
 '10884554436911104',
 '28753643951',
 '25721001008',
 '19057529262710784',
 '26299015109',
 '513206812413952',
 '28978827369',
 '25726227901',
 '19397230003757056',
 '26785427201',
 '4278014154117120',
 '25284011603',
 '24186491208',
 '29469533494',
 '8613892766834688',
 '25163471303',
 '26716455901',
 '3144729948585984',
 '28562490854',
 '29431358910',
 '25393706802',
 '28809507841',
 '26344555407',
 '24932626903',
 '7873648274706433',
 '6149176928772096',
 '12489790410723329',
 '6757497738100736',
 '23186911703',
 '2451776326340608',
 '24946400602',
 '2566692005740545',
 '2987464402665473',
 '22927828508',
 '29302608791',
 '17973142412595200',
 '26270084908',
 '2202592805392384',
 '25916414309',
 '20422850909310976',
 '11780050978349058',
 '9350278289555456',
 '9132522726236160',
 '29399102331',
 '25598565402',
 '7314287475302400',
 '7182296884973568',
 '27968992745',
 '17290448175374336',
 '16848552986677248',
 '24399259900',
 '23192089902',
 '20850934137495552',
 '28557774753',
 '24933887606',
 '18340596875788289',
 '10267283297411072',
 '1585887674638336',
 '28549955532',
 '24719532802',
 '29511653171',
 '13353720288903168',
 '4214772576821248',
 '2393005684166656',
 '961397773045760',
 '17015762921193473',
 '27560176169',
 '27110560308',
 '18325564397981696',
 '6766318732705792',
 '28375443721',
 '383775011774464',
 '4736820738789377',
 '28514820560',
 '29206790724',
 '24867720809',
 '4344107962998784',
 '5736877046898688',
 '15460515065110528',
 '1762832416776192',
 '24151313001',
 '24211826103',
 '25597380109',
 '17047866132402177',
 '26141010908',
 '3903458688110592',
 '11937429996969984',
 '28544210861',
 '14759437143113728',
 '16323543419588610',
 '20039445050826752',
 '26284893203',
 '13459957999472640',
 '4399586009423872',
 '27170388778',
 '2000637105545216',
 '25900802108',
 '20626194902810624',
 '12872847739330560',
 '20367309629558784',
 '16382905672540161',
 '8916956434403328',
 '29593263419',
 '26292098509',
 '17193777756114944',
 '27879445366',
 '29427432220',
 '19988207567372288',
 '12731348569563136',
 '28361756786',
 '22828698409',
 '28531159692',
 '295564344295424',
 '22825089503',
 '27491736357',
 '27672533719',
 '29273671860',
 '20667818919858177',
 '14491815600201728',
 '17692639763636224',
 '27185319376',
 '15775209751576576',
 '22917752005',
 '24751827000',
 '8933288949325824',
 '19183261766918145',
 '1735020066643968',
 '24227456703',
 '23157157907',
 '26152655303',
 '26850659302',
 '27214067621',
 '24289638309',
 '15569068039872512',
 '29431895081',
 '25785113608',
 '11937228527767552',
 '15539456052301824',
 '7644501065601024',
 '29326660399',
 '13699490418532352',
 '451604935352320',
 '19572250046894080',
 '7209400607440896',
 '23097047902',
 '24105443500',
 '26569330601',
 '6757661303373824',
 '12198319522578432',
 '20276369036410880',
 '24302421507',
 '26419435708',
 '27408505672',
 '4413376981635072',
 '28370483899',
 '19891046339055616',
 '17567419002265600',
 '25330870303',
 '27921920479',
 '983635888967680',
 '28657071768',
 '26134886404',
 '13322728580849665',
 '25064486205',
 '25154647808',
 '2123861357232128',
 '25395447706',
 '2124520106229760',
 '9259157177765890',
 '19420902898794496',
 '23948685200',
 '25713158509',
 '14353201935421441',
 '24258608001',
 '17013368070082560',
 '2944116300189696',
 '1359994985390081',
 '19184398674960385',
 '26567805907',
 '5637111113842690',
 '13396363874140160',
 '28557938465',
 '24186176309',
 '22854877908',
 '24824249607',
 '653363897171968',
 '4367033860882432',
 '26101882201',
 '22833997901',
 '6446301541564416',
 '27986763232',
 '1300410610487296',
 '5650625362661376',
 '27593558653',
 '24976977800',
 '10847900703662081',
 '29494579549',
 '25035267302',
 '24806392209',
 '22993646604',
 '4326210863628288',
 '28361966609',
 '29508653316',
 '2722661343952897',
 '29340219807',
 '28610987295',
 '25909941305',
 '27368558337',
 '11341981280116736',
 '13065773253660672',
 '28058067833',
 '22862568105',
 '25973136108',
 '26593735008',
 '24899970100',
 '8906705417019392',
 '27174635407',
 '27266529608',
 '29557083234',
 '24635446402',
 '4996343219101696',
 '20331305992454144',
 '23933078803',
 '28533313375',
 '6572218737758209',
 '8731626687176705',
 '25083818902',
 '28369518307',
 '25248816301',
 '1842885272018944',
 '16613260660842496',
 '27786560324',
 '13691416328806400',
 '1781845498789888',
 '20623493435490304',
 '14042597135745024',
 '11824938516221952',
 '24524597200',
 '27521728628',
 '18336805359190017',
 '20221146632822785',
 '25565664403',
 '25870662708',
 '5768078189142016',
 '13677546046492672',
 '26104903007',
 '25170456500',
 '29680765625',
 '7775946199273472',
 '23923555207',
 '25391326509',
 '26903388309',
 '4257940269694976',
 '27814304209',
 '10828950905298945',
 '26305476305',
 '14478171319574528',
 '24583983604',
 '28558869888',
 '26578024501',
 '20907636824219648',
 '25353461504',
 '29397368003',
 '22853422806',
 '26259795600',
 '20582284637769728',
 '912986906562560',
 '24129189309',
 '26274095107',
 '23174168906',
 '3495205877587969',
 '5303362153095169',
 '28561176626',
 '14519573348880384',
 '11240156161900545',
 '27079929406',
 '26551242804',
 '27259225394',
 '967466851241986',
 '27715609194',
 '8988519485673472',
 '14043792315252736',
 '23208008100',
 '6372901024432129',
 '1305003348205569',
 '19540075528327169',
 '24588097704',
 '11433408777428992',
 '1729072476459008',
 '24762058307',
 '27645908506',
 '27461513878',
 '27403061425',
 '6875009700069376',
 '27647098959',
 '20679802272882688',
 '13995201534107648',
 '14198667305025537',
 '20970022922883073',
 '24044847208',
 '27099447605',
 '1726958727593984',
 '29431485663',
 '6760303740063744',
 '12869529872891905',
 '27949607437',
 '14181722346225664',
 '27659141086',
 '16201829025058818',
 '364686662959104',
 '24945473806',
 '20204541223903232',
 '29321251637',
 '6371558922657792',
 '8165118718255105',
 '5823673948700672',
 '1727508290478080',
 '16137287054135296',
 '29431578248',
 '29031118578',
 '29431532895',
 '16550547519705088',
 '22855475505',
 '29497053605',
 '22771231208',
 '29398615145',
 '24387546705',
 '29006077623',
 '11605622676000768',
 '26148299103',
 '26804799004',
 '25709160107',
 '1337144131985409',
 '24664579004',
 '25691779401',
 '27843153753',
 '19780149255872512',
 '15195493915172867',
 '25450325506',
 '24309840101',
 '25343407007',
 '27968709974',
 '17113242862092288',
 '24407965702',
 '14485230362566656',
 '29353602154',
 '23241186206',
 '27585881254',
 '24226281907',
 '8275429051867136',
 '19606798369558528',
 '11574744205754368',
 '13424679771447297',
 '28733557528',
 '28748167889',
 '24869654709',
 '19996549891231744',
 '16982623825960960',
 '20858060046082049',
 '5643193047580673',
 '7823832773558272',
 '3830678974111745',
 '1791668286132224',
 '14424585130737664',
 '25056179505',
 '11657783082491904',
 '26414486904',
 '9576015651147776',
 '6580762673414145',
 '10446279318437888',
 '25248240706',
 '3210618307870720',
 '24143425704',
 '12758242555858944',
 '22859864801',
 '2921043400331264',
 '25369826607',
 '29473623833',
 '13381398790414336',
 '20177081216278528',
 '22844160402',
 '18867263109070848',
 '27639214024',
 '28561372282',
 '14403588327473152',
 '15610411105648640',
 '3259884682346496',
 '26150858405',
 '20491746362265600',
 '26383586709',
 '24098222404',
 '6863869578313728',
 '16526988185436160',
 '25592383704',
 '5858675159732224',
 '22843986403',
 '29430743250',
 '28510811061',
 '29607994158',
 '27990187760',
 '29287403331',
 '26977697500',
 '8354043088863233',
 '29446753493',
 '28471898134',
 '20402235871600640',
 '26952098800',
 '29627260764',
 '7232121164800000',
 '29296573748',
 '25543282200',
 '10563409254813696',
 '26758712001',
 '13260418013208576',
 '29429507155',
 '22856869902',
 '19117910546980865',
 '23176394907',
 '28953088012',
 '10025703923781632',
 '25150225402',
 '25960037106',
 '29014698342',
 '17263394855845888',
 '25249989806',
 '8888606819094528',
 '1788027680595968',
 '27556357566',
 '24301814806',
 '27978411468',
 '11510327917150208',
 '27648295232',
 '24254771304',
 '6148744919654400',
 '29060301528',
 '26769704709',
 '24062546702',
 '23092179804',
 '19922252283772928',
 '26394776000',
 '19972927747260416',
 '28370287481',
 '27538916624',
 '625698045689856',
 '27857394891',
 '5053519962836992',
 '16584852769869824',
 '23118420009',
 '15885209417285632',
 '386572604145665',
 '29697449126',
 '2535997833220097',
 '17455674430586881',
 '29208678090',
 '26130331106',
 '15154356164763648',
 '28773964667',
 '26400147202',
 '26570555405',
 '2856719759708160',
 '29608327730',
 '7999779384594432',
 '27038163804',
 '29036770370',
 '27062792602',
 '23958123803',
 '16521464270299136',
 '10589447460487168',
 '10368743527948289',
 '25124092500',
 '22902513608',
 '20320803312635904',
 '27495225317',
 '24947547302',
 '10140099358490624',
 '22838065106',
 '28360574652',
 '14359564841394176',
 '11530905453600768',
 '17203491768377344',
 '28572078647',
 '24964411509',
 '19959145385955330',
 '3471499897864192',
 '12926694067281920',
 '22921996602',
 '26199032703',
 '577534894809089',
 '18348536877813761',
 '16288596726124544',
 '17684515434528768',
 '29406163763',
 '24282412604',
 '29058636252',
 '6845096095916032',
 '24729640802',
 '10429317360132096',
 '27074271107',
 '16485439615541248',
 '25240668303',
 '23060397705',
 '26420833609',
 '25121294702',
 '11919327204737024',
 '8556187482062848',
 '23247295309',
 '19818002543288321',
 '18474130751885312',
 '27282311830',
 '19745227497537536',
 '27031170208',
 '26033629807',
 '18021989276983297',
 '1311814969204737',
 '15810038975168512',
 '5088320178622464',
 '25735541306',
 '19809018558025729',
 '24900192308',
 '12525567869980672',
 '13000610433470465',
 '27066824603',
 '20653839363342336',
 '26542771001',
 '28751526241',
 '29512123206',
 '6760824169299969',
 '29501893449',
 '9314161234284544',
 '6404937491685377',
 '9859571652759552',
 '6147331535675393',
 '23138096500',
 '27099322709',
 '20610449217159168',
 '26209020906',
 '24327082306',
 '14114659435020290',
 '20220647384809472',
 '13691890448732160',
 '9997195029782529',
 '5003209357660160',
 '27744415681',
 '25712193805',
 '4371572399808512',
 '20519630015561729',
 '26287752409',
 '26709630001',
 '25176700609',
 '25250312804',
 '23892979404',
 '16248754713665536',
 '3851948147085313',
 '25851409201',
 '19594228342464512',
 '12212215574700032',
 '26021623206',
 '19252681730162689',
 '13424725686489088',
 '5636507423477760',
 '26717234907',
 '20919448101724160',
 '24911422106',
 '9817418897555456',
 '28394677764',
 '29398637687',
 '20424448939130880',
 '5117663529402368',
 '29431438773',
 '25166544906',
 '29400806904',
 '8957309652836352',
 '13379523739385856',
 '10816749624627200',
 '20877655805001728',
 '29397427722',
 '15595210822127616',
 '4369236176666624',
 '11929183659753472',
 '22921194604',
 '4248553140518912',
 '25733313808',
 '25933592907',
 '17602973869801473',
 '17060205783158784',
 '9702499107741696',
 '26315343101',
 '14410689158324224',
 '17281010689380352',
 '4338722296299520',
 '27902567083',
 '8909704189181952',
 '10396102641590273',
 '26439967805',
 '6832131233808384',
 '24279955006',
 '10921347270049792',
 '29629438500',
 '9304862395207680',
 '14853481881927681',
 '27470755719',
 '4209294484443136',
 '26549429102',
 '24122382307',
 '968754208964608',
 '7156971811643392',
 '29600873940',
 '29427834638',
 '13388931735232512',
 '28498754812',
 '12208763452788737',
 '26213810703',
 '16860532023754752',
 '24308986002',
 '23165519103',
 '19029729478713345',
 '24000638205',
 '11095410747645952',
 '26265869303',
 '8924342658277377',
 '29316778445',
 '20653281692880896',
 '24321158001',
 '24854965408',
 '2133764415164416',
 '7163716374102017',
 '3222844888584192',
 '28355736166',
 '26790459809',
 '28364190552',
 '12917118727094272',
 '3093861601648640',
 '24869794008',
 '27385735629',
 '28571199031',
 '6762514142470144',
 '11496805678190592',
 '24283625006',
 '27681460266',
 '25440140300',
 '25399535807',
 '24203263904',
 '14978262597902336',
 '28471868400',
 '25012437401',
 '27313089656',
 '7991885960318976',
 '26746894907',
 '27273464749',
 '24797833209',
 '8892474068045824',
 '26612240503',
 '22850885406',
 '25239269802',
 '29406964375',
 '23162990108',
 '14489550730563586',
 '17654299890814976',
 '6388298536722433',
 '26506756202',
 '29431254499',
 '24729309105',
 '27136032544',
 '27586391663',
 '24183352604',
 '5096603857719296',
 '29118194819',
 '25367015200',
 '29608433786',
 '20912326035116032',
 '11501750691307521',
 '14384621441515520',
 '2257282339442688',
 '26090995202',
 '24323215804',
 '27705849358',
 '13215295799820288',
 '24935152806',
 '7886939940192256',
 '23272601808',
 '28729891271',
 '713216384565248',
 '24724625205',
 '29432899967',
 '8924854132678656',
 '12224882364391424',
 '25167045206',
 '15507541802881024',
 '20848635285602304',
 '25243835400',
 '11545459466178561',
 '19089535824568320',
 '19051980265627648',
 '1085230119129089',
 '24940293403',
 '28553037304',
 '17580438088327170',
 '29584419331',
 '26284009008',
 '10679696282877952',
 '9468297602932736',
 '711618543489024',
 '19062373834817537',
 '29436597962',
 '6209365426044928',
 '29410371273',
 '373171547021313',
 '28561938760',
 '12242804549885952',
 '26621514905',
 '17605683402768384',
 '3063045840441344',
 '23866727907',
 '25049564906',
 '24257271305',
 '19489588703666176',
 '594345510043648',
 '19519708126511104',
 '940568846794752',
 '19084297214369792',
 '24201234600',
 '15561337950183424',
 '25155538600',
 '20649636926590976',
 '23877119203',
 '28051070403',
 '27593326627',
 '14734363539283970',
 '6858395957067776',
 '19500867208085505',
 '687945925263361',
 '25607472808',
 '27892596922',
 '27220375511',
 '18572776952569856',
 '24543669609',
 '26803070208',
 '27745076755',
 '2381060516085760',
 '24062909500',
 '24144404808',
 '25013119709',
 '1076074012213248',
 '22807102407',
 '1311995244584960',
 '25278600301',
 '26261234008',
 '27043194008',
 '24949902104',
 '11949320571985921',
 '13506539704819712',
 '9782031395332096',
 '26816343401',
 '29224731595',
 '12894930569531392',
 '29325292177',
 '20961550277808129',
 '1092507337236480',
 '11560982497198081',
 '29306460054',
 '20955225363845120',
 '12273271894441985',
 '2043855163625472',
 '26973571200',
 '26713939403',
 '12895467595636736',
 '19974001421979648',
 '23073854805',
 '24007824401',
 '12516025702547456',
 '28815890450',
 '12609017431982080',
 '24380833007',
 '7158125207486464',
 '6490685712637954',
 '20712509526777856',
 '29583806786',
 '29013463298',
 '29400938291',
 '1682586992644096',
 '19905600930455552',
 '7910805697724416',
 '28909801196',
 '4649986000162817',
 '18161885882884096',
 '27574948332',
 '25047455006',
 '18394913297137664',
 '9980082466590720',
 '28551775307',
 '23948382301',
 '25608491607',
 '28050839230',
 '27753801758',
 '24617544902',
 '9720505288359936',
 '14779234308333569',
 '12819571656359936',
 '29676158922',
 '18298796387606528',
 '2204354245304320',
 '4367063304900608',
 '23994279706',
 '6837760291770368',
 '25123070101',
 '26397122105',
 '10181169748381696',
 '29050599318',
 '26680218004',
 '26663980403',
 '26103842502',
 '26309655103',
 '26507821004',
 '29432462688',
 '15680460206116864',
 '27520698673',
 '28929511961',
 '28731041624',
 '22887977300',
 '27212755747',
 '26265812601',
 '20201294916485120',
 '25113258206',
 '7946214028877824',
 '29508983096',
 '22829676603',
 '11221684262543360',
 '16922171284656130',
 '18082383039303681',
 '17686880883572736',
 '9736657548877824',
 '29047076534',
 '25914259500',
 '23008880106',
 '24913448403',
 '1783040594411520',
 '24894222509',
 '29336915991',
 '26259268606',
 '20977476238835713',
 '24759504303',
 '28359138006',
 ...]

In [12]:
header_list = ["tweet_ID", "tweet_text"]
tweets_2010 = pd.read_csv("2010alltweets.txt", names=header_list, sep="\t")

In [14]:
a = tweets_2010.head()

In [24]:
b = add_sentiment(a)

<ipython-input-22-9abf82479949>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment'] = df['tweet_text'].apply(lambda x: get_sentiment(str(x)))

In [27]:
pd.set_option('display.max_colwidth', -1)
b

<ipython-input-27-55a8d4a31ccb>:1: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

,tweet_ID,tweet_text,sentiment
0,22662042404,Can someone please tell me WTF the #Seahawks are doing? #retards,-0.4995
1,22662135903,Q&A with Todd Haley - 8/31 #NFL #chiefs http://tinyurl.com/333m7np,0.0000
2,22662138503,PFW Blog: Bodden done for the year #NFL #patriots http://tinyurl.com/34glgfb,0.0000
3,22662142404,"Bomar the backup for Giants, for now #NFL #giants http://tinyurl.com/39fmylf",0.0000
4,22662229101,"#Packers made the right moves 2day. Tough decisions in week 7, but Peprah will help ST's & Starks may b ready by then, which would b a boost",0.8779

In [31]:
# Clean the tweets
b['tweet_text'] = b['tweet_text'].apply(cleanTxt)

<ipython-input-31-bc71563caac6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  b['tweet_text'] = b['tweet_text'].apply(cleanTxt)

In [32]:
b

,tweet_ID,tweet_text,sentiment
0,22662042404,Can someone please tell me WTF the Seahawks are doing? retards,-0.4995
1,22662135903,Q&A with Todd Haley - 8/31 NFL chiefs,0.0000
2,22662138503,PFW Blog: Bodden done for the year NFL patriots,0.0000
3,22662142404,"Bomar the backup for Giants, for now NFL giants",0.0000
4,22662229101,"Packers made the right moves 2day. Tough decisions in week 7, but Peprah will help ST's & Starks may b ready by then, which would b a boost",0.8779

### Functions and Imports

In [113]:
import re
import nltk
#from textblob import TextBlob
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')

def get_sentiment(tweet):
    analyzer = SentimentIntensityAnalyzer()
    return analyzer.polarity_scores(tweet)['compound']

def add_sentiment(df):
    df['sentiment'] = df['text'].apply(lambda x: get_sentiment(str(x)))
    return df

def cleanTxt(text):
    text = re.sub('@[A-Za-z0–9]+', '', text) #Removing @mentions
    text = re.sub('#', '', text) # Removing '#' hash tag
    text = re.sub('RT[\s]+', '', text) # Removing RT
    text = re.sub('https?:\/\/\S+', '', text) # Removing hyperlink
    return text

def make_twitter_df(year):
    year = str(year)
    tweets_file_name = year+"alltweets.txt"
    tweets_header_list = ['id','text']
    tweets_df = pd.read_csv(tweets_file_name, names=tweets_header_list, sep='\t',error_bad_lines=False)
    tweets_df = tweets_df.dropna()
    tweets_df['text'] = tweets_df['text'].apply(cleanTxt)
    tweets_df['id'] = tweets_df['id'].apply(int)
    
    data_header_list = ["id", "tweet_time","team","opponent", "week", "home_or_away","score","opponent_score","point_spread","over_under"]
    data_df = pd.read_csv('nfl-tweets-v1.0/tweets.nfl.'+year+'.weekly.csv', names=data_header_list)
    
    combined_df = pd.merge(data_df,tweets_df,on='id').dropna()
    sent_df = add_sentiment(combined_df)
    
    final_df = sent_df[["team", "week","sentiment","text"]]
    final_df = final_df.groupby(['team','week'],as_index=False)['sentiment'].mean()

    return final_df

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/stanierc17/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [114]:
df = make_twitter_df(2011)

In [115]:
df.to_csv("2011sentiment.csv",index=False)

# Step 1: Prepare Dataframe

In [88]:
# The only thing you need to change for the different datasets
year = "2010"

# Here I'm putting everything into a dataframe and cleaning the text
tweets_file_name = year+"alltweets.txt"
tweets_header_list = ['id','text']
tweets_df = pd.read_csv(tweets_file_name, names=tweets_header_list, sep='\t',error_bad_lines=False)
tweets_df = tweets_df.dropna()
tweets_df['text'] = tweets_df['text'].apply(cleanTxt)
tweets_df['id'] = tweets_df['id'].apply(int)
tweets_df.head()

,id,text
0,22662042404,Can someone please tell me WTF the Seahawks are doing? retards
1,22662135903,Q&A with Todd Haley - 8/31 NFL chiefs
2,22662138503,PFW Blog: Bodden done for the year NFL patriots
3,22662142404,"Bomar the backup for Giants, for now NFL giants"
4,22662229101,"Packers made the right moves 2day. Tough decisions in week 7, but Peprah will help ST's & Starks may b ready by then, which would b a boost"

In [89]:
data_header_list = ["id", "tweet_time","team","opponent", "week", "home_or_away","score","opponent_score","point_spread","over_under"]
data_df = pd.read_csv('nfl-tweets-v1.0/tweets.nfl.'+year+'.weekly.csv', names=data_header_list)
data_df.head()

,id,tweet_time,team,opponent,week,home_or_away,score,opponent_score,point_spread,over_under
0,22662042404,2010-9-01T00:18:50,SEA,SF,1,HOME,31,6,3.0,37.0
1,22662135903,2010-9-01T00:20:06,KC,SD,1,HOME,21,14,5.0,44.5
2,22662138503,2010-9-01T00:20:08,NE,CIN,1,HOME,38,24,-5.5,44.5
3,22662142404,2010-9-01T00:20:11,NYG,CAR,1,HOME,31,18,-6.0,41.0
4,22662225702,2010-9-01T00:21:18,DEN,JAX,1,AWAY,17,24,3.0,41.0

# Step 2: Add Sentiment

In [90]:
combined_df = pd.merge(data_df,tweets_df,on='id').dropna()
combined_df.head()

,id,tweet_time,team,opponent,week,home_or_away,score,opponent_score,point_spread,over_under,text
0,22662042404,2010-9-01T00:18:50,SEA,SF,1,HOME,31,6,3.0,37.0,Can someone please tell me WTF the Seahawks are doing? retards
1,22662135903,2010-9-01T00:20:06,KC,SD,1,HOME,21,14,5.0,44.5,Q&A with Todd Haley - 8/31 NFL chiefs
2,22662138503,2010-9-01T00:20:08,NE,CIN,1,HOME,38,24,-5.5,44.5,PFW Blog: Bodden done for the year NFL patriots
3,22662142404,2010-9-01T00:20:11,NYG,CAR,1,HOME,31,18,-6.0,41.0,"Bomar the backup for Giants, for now NFL giants"
4,22662229101,2010-9-01T00:21:20,GB,PHI,1,AWAY,27,20,-3.0,48.0,"Packers made the right moves 2day. Tough decisions in week 7, but Peprah will help ST's & Starks may b ready by then, which would b a boost"

In [91]:
sent_df = add_sentiment(combined_df)

# Step 3: Extract Weekly Average Sentiment

In [104]:
final_df = sent_df[["team", "week","sentiment","text"]]
final_df = final_df.groupby(['team','week'],as_index=False)['sentiment'].mean()

In [107]:
final_df.to_csv("2010sentiment.csv",index=False)

In [105]:
final_df.head()

  team  week  sentiment
0  ARI  1     0.180404
1  ARI  2     0.116099
2  ARI  3     0.088700
3  ARI  4     0.192257
4  ARI  5     0.057983

In [109]:
final_df

    team  week  sentiment
0    ARI  1     0.180404
1    ARI  2     0.116099
2    ARI  3     0.088700
3    ARI  4     0.192257
4    ARI  5     0.057983
..   ... ..          ...
507  WAS  13    0.121189
508  WAS  14    0.080666
509  WAS  15    0.051873
510  WAS  16    0.105535
511  WAS  17    0.191555

[512 rows x 3 columns]